spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type=rest
spark.sql.catalog.local.uri=http://rest:8181
spark.sql.catalog.local.warehouse=s3://warehouse/
spark.sql.defaultCatalog=local